PATH="$HOME/usr/local/bin":'/usr/local/bin':'/usr/local/sbin':$PATH

export PS1='\[\033[0;32m\]\u@\h \[\033[1;34m\]\W $ \[\033[m\]'

source '/usr/local/etc/bash_completion.d/git-completion.bash'
source "$HOME/.bash_completions/django"

alias pg_run='postgres -D /usr/local/var/postgres'
alias my_run='mysql.server start'
alias mongo_run='ulimit -n 2048 && mongod --config /usr/local/etc/mongod.conf'
alias pinknoise='play -t sl -r 8k -c 2 - synth 30:00:00 pinknoise band -n 1200 200 tremolo 20 .1 </dev/zero 2</dev/null'
alias qmake5="/usr/local/Cellar/qt5/$(ls /usr/local/Cellar/qt5 | tail -n 1)/bin/qmake"

alias ll='ls -aFhl'
alias la='ls -A'
alias l='ls -CF'

alias gut=git

killport() {
    lsof -i TCP:$1 | grep LISTEN | awk '{print $2}' | xargs kill -9
}

set-title() {
    echo -n -e "\033]0;$1\007"
}

macdown() {
    "$(mdfind kMDItemCFBundleIdentifier=com.uranusjr.macdown | head -n1)/Contents/SharedSupport/bin/macdown" $@
}

subl() {
    "$(mdfind kMDItemCFBundleIdentifier=com.sublimetext.3 | head -n1)/Contents/SharedSupport/bin/subl" $@
}

mkvenv() {
    $(python3 -c "import sys; print(sys.executable)") -m venv $1
    . $1/bin/activate
    pip install -qU pip setuptools
}

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

export EDITOR=vim

export WORKON_HOME=$HOME/Documents/programming/virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
source '/usr/local/bin/virtualenvwrapper.sh'
source '/usr/local/opt/autoenv/activate.sh'

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
PATH="$HOME/.rbenv/shims:$PATH"

export ANDROID_HOME=/usr/local/opt/android-sdk

export PATH
