PATH='/usr/local/sbin':"$HOME/usr/local/bin":$PATH

export PS1='\[\033[0;32m\]\u@\h \[\033[1;34m\]\W $ \[\033[m\]'

source '/usr/local/etc/bash_completion.d/git-completion.bash'
for f in $(ls $HOME/.bash_completions/*.bash); do
    source "$f"
done

alias pg_run='pg_ctl start'
alias my_run='mysql.server start'
alias mongo_run='ulimit -n 2048 && mongod --fork --config /usr/local/etc/mongod.conf'
alias pinknoise='play -t sl -r 8k -c 2 - synth 30:00:00 pinknoise band -n 1200 200 tremolo 20 .1 </dev/zero 2</dev/null'
alias qmake5="/usr/local/Cellar/qt5/$(ls /usr/local/Cellar/qt5 | tail -n 1)/bin/qmake"

killport() {
    lsof -i TCP:$1 | grep LISTEN | awk '{print $2}' | xargs kill -9
}

set-title() {
    echo -n -e "\033]0;$1\007"
}

macdown() {
    "$(mdfind kMDItemCFBundleIdentifier=com.uranusjr.macdown | awk '!/\/Users/{print;exit}')/Contents/SharedSupport/bin/macdown" $@
}

subl() {
    "$(mdfind kMDItemCFBundleIdentifier=com.sublimetext.3 | head -n1)/Contents/SharedSupport/bin/subl" $@
}

mkvenv() {
    VENV_DIR=$1
    if [ -z "$VENV_DIR" ]; then
        VENV_DIR="venv/$(basename $PWD)"
    fi
    echo "Creating venv at $VENV_DIR"
    $(python3 -c "import sys; print(sys.executable)") -m venv $VENV_DIR
    . $VENV_DIR/bin/activate
    pip install -qU pip setuptools
}

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

export EDITOR=vim

export WORKON_HOME=$HOME/Documents/programming/virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
source '/usr/local/bin/virtualenvwrapper.sh'

export AUTOENV_ENV_FILENAME='.autoenv'
source "$HOME/Documents/programming/misc/autoenv/autoenv/activate.sh"

if 'which' -s pyenv; then eval "$(pyenv init -)"; fi

if 'which' -s rbenv; then eval "$(rbenv init -)"; fi
PATH="$HOME/.rbenv/shims:$PATH"

export DOCKERVM=docker-vm

docker-machine-source() {
    eval $(docker-machine env $DOCKERVM)
}
docker-machine-reload() {
    docker-machine restart $DOCKERVM
    docker-machine-source
}

if [ $(docker-machine status $DOCKERVM) != 'Running' ]; then
    docker-machine start $DOCKERVM
fi
docker-machine-source

export CUTESHOP_EXTRA_SPEC_SOURCES="$HOME/Documents/programming/misc/cuteshop-private/specs/"

alias ll='ls -aFhl'
alias la='ls -A'
alias l='ls -CF'

alias gut=git
alias fit=git
alias which=gwhich

export PGDATA=/usr/local/var/postgres

export ANDROID_HOME=/usr/local/opt/android-sdk

export PATH
